// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type Device struct {
	ID     string       `json:"id"`
	Name   string       `json:"name"`
	Status *Status      `json:"status"`
	Group  *DeviceGroup `json:"group"`
	Os     string       `json:"os"`
}

type DeviceGroup struct {
	ID           string        `json:"id"`
	Name         string        `json:"name"`
	Devices      []*Device     `json:"devices"`
	Installation *Installation `json:"installation"`
}

type Installation struct {
	ID       string         `json:"id"`
	Name     string         `json:"name"`
	Location string         `json:"location"`
	Groups   []*DeviceGroup `json:"groups"`
	Devices  []*Device      `json:"devices"`
}

type Status struct {
	State    string `json:"state"`
	CPU      *int   `json:"cpu"`
	MemoryMb *int   `json:"memoryMb"`
}
